// AUTH
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_LOGIN = "SET_LOGIN";
export const SET_SIGNUP = "SET_SIGNUP";

// STUDENT
export const SET_STUDENT_DATA = "SET_STUDENT_DATA";
export const SET_STUDENT_DUE_AMOUNT_LIST = "SET_STUDENT_DUE_AMOUNT_LIST";

// ERROR
export const SET_ERROR = "SET_ERROR";

// SET_LOADING_STATUS
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
